language: erlang

branches:
    only:
        - master

otp_release:
    - 21.3
    - 22.3
    - 23.0

install:
    - make
    - make test-compile
    - travis_retry pip install --user codecov

script:
    - make test
    - make dialyzer

after_success:
    - make codecov
    - codecov
