name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['24.2', '23.3']
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: '3.18.0'
      - run: rebar3 as test compile
      - run: rebar3 ct
      - run: rebar3 ex_doc
        if: ${{ matrix.otp == '24.2' }}
      - run: rebar3 dialyzer
        if: ${{ matrix.otp == '24.2' }}
      - run: pip install --user codecov
        if: ${{ matrix.otp == '24.2' }}
      - run: rebar3 as test codecov analyze
        if: ${{ matrix.otp == '24.2' }}
      - run: gcov -o c_src mongoose_jid
        if: ${{ matrix.otp == '24.2' }}
      - run: /home/runner/.local/bin/codecov
        if: ${{ matrix.otp == '24.2' }}
